title: Pandanautinspace
description: Kenneth Browder's website.
google_analytics: 
show_downloads: false
remote_theme: kitian616/jekyll-TeXt-theme

gems:
  - jekyll-mentions

theme: jekyll-theme-cayman